# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SimpleCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 450)
        MainWindow.setMinimumSize(QtCore.QSize(350, 450))
        MainWindow.setMaximumSize(QtCore.QSize(350, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.number7 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.pressed("7"))
        self.number7.setGeometry(QtCore.QRect(10, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number7.setFont(font)
        self.number7.setObjectName("number7")
        
        self.division_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.pressed("/"))
        self.division_button.setGeometry(QtCore.QRect(250, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.division_button.setFont(font)
        self.division_button.setObjectName("division_button")
        
        self.number9 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.pressed("9"))
        self.number9.setGeometry(QtCore.QRect(170, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number9.setFont(font)
        self.number9.setObjectName("number9")
        
        self.number6 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.pressed("6"))
        self.number6.setGeometry(QtCore.QRect(170, 190, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number6.setFont(font)
        self.number6.setObjectName("number6")
        
        self.number3 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.pressed("3"))
        self.number3.setGeometry(QtCore.QRect(170, 260, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number3.setFont(font)
        self.number3.setObjectName("number3")
        
        self.equal_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.calculate())
        self.equal_button.setGeometry(QtCore.QRect(170, 330, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.equal_button.setFont(font)
        self.equal_button.setObjectName("equal_button")
        
        self.clear_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.pressed("C"))
        self.clear_button.setGeometry(QtCore.QRect(90, 330, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear_button.setFont(font)
        self.clear_button.setObjectName("clear_button")
        
        self.number2 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.pressed("2"))
        self.number2.setGeometry(QtCore.QRect(90, 260, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number2.setFont(font)
        self.number2.setObjectName("number2")
        
        self.number5 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.pressed("5"))
        self.number5.setGeometry(QtCore.QRect(90, 190, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number5.setFont(font)
        self.number5.setObjectName("number5")
        
        self.number8 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.pressed("8"))
        self.number8.setGeometry(QtCore.QRect(90, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number8.setFont(font)
        self.number8.setObjectName("number8")
        
        self.number0 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.pressed("0"))
        self.number0.setGeometry(QtCore.QRect(10, 330, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number0.setFont(font)
        self.number0.setObjectName("number0")
        
        self.number1 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.pressed("1"))
        self.number1.setGeometry(QtCore.QRect(10, 260, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number1.setFont(font)
        self.number1.setObjectName("number1")
        
        self.number4 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.pressed("4"))
        self.number4.setGeometry(QtCore.QRect(10, 190, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number4.setFont(font)
        self.number4.setObjectName("number4")
        
        self.mult_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.pressed("*"))
        self.mult_button.setGeometry(QtCore.QRect(250, 190, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mult_button.setFont(font)
        self.mult_button.setObjectName("mult_button")
        
        self.sum_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.pressed("+"))
        self.sum_button.setGeometry(QtCore.QRect(250, 330, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sum_button.setFont(font)
        self.sum_button.setObjectName("sum_button")
        
        self.sub_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.pressed("-"))
        self.sub_button.setGeometry(QtCore.QRect(250, 260, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sub_button.setFont(font)
        self.sub_button.setObjectName("sub_button")
        
        self.text_area = QtWidgets.QLabel(self.centralwidget)
        self.text_area.setGeometry(QtCore.QRect(10, 40, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.text_area.setFont(font)
        self.text_area.setAutoFillBackground(False)
        self.text_area.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.text_area.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.text_area.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_area.setObjectName("text_area")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def calculate(self):
        screen = self.text_area.text()
        try:
            answer = eval(screen)
        except:
            self.text_area.setText("ERROR!")
        else:
            self.text_area.setText(str(answer))
    
    def pressed(self, buttonPressed):
        if buttonPressed == "C":
            self.text_area.setText("0")
        else:
            if self.text_area.text() == "0" or self.text_area.text() == "ERROR!" :
                self.text_area.setText("")
            self.text_area.setText(f"{self.text_area.text()}{buttonPressed}")
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SimpleCalculator"))
        self.number7.setText(_translate("MainWindow", "7"))
        self.division_button.setText(_translate("MainWindow", "/"))
        self.number9.setText(_translate("MainWindow", "9"))
        self.number6.setText(_translate("MainWindow", "6"))
        self.number3.setText(_translate("MainWindow", "3"))
        self.equal_button.setText(_translate("MainWindow", "="))
        self.clear_button.setText(_translate("MainWindow", "C"))
        self.number2.setText(_translate("MainWindow", "2"))
        self.number5.setText(_translate("MainWindow", "5"))
        self.number8.setText(_translate("MainWindow", "8"))
        self.number0.setText(_translate("MainWindow", "0"))
        self.number1.setText(_translate("MainWindow", "1"))
        self.number4.setText(_translate("MainWindow", "4"))
        self.mult_button.setText(_translate("MainWindow", "*"))
        self.sum_button.setText(_translate("MainWindow", "+"))
        self.sub_button.setText(_translate("MainWindow", "-"))
        self.text_area.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
